//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyVersionAttribute("0.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1.0")]

// Generated by the MSBuild WriteCodeFragment class on 9/17/2013 10:16:40 PM.

